### ISSUE TITLE
I made a Jupyter notebook that parses ScrapeMate's export files and attempts to scrape the data from the webpage with Pyppeteer

### ISSUE THREAD

**Issue by sergeyyurkov1** [Unknowny/ScrapeMate#3]
https://github.com/sergeyyurkov1/ScrapeMate_Companion/blob/main/TGStat.ipynb

Please take a look and tell me what you think. If you are interested, this can be made into a full Python package.

Thanks for a great tool.

**Comment by hermit-crab** [comment]
Hey there @sergeyyurkov1. Apologies for a (very) late reply, got to get myself to configure github email notifications properly.

Your use case seems perfectly good to me, in fact more or less how I Intended initially _"pick all the needed selectors via ScrapeMate then use the resulting instruction text inside the actual scraping software be it pyppeteer or (in my case at the time) scrapy"_. Feel completely free to create a package with any complementary functionality that you see value in.
